#RUN THIS SCRIPT FIRST TO DROP THE USERS TABLE AND START FROM SCRATCH

DROP TABLE USERS;

#RUN THIS SCRIPT SECOND TO CREATE THE NEW USERS TABLE

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `username` varchar(32) DEFAULT NULL,
  `first_name` varchar(32) NOT NULL,
  `last_name` varchar(50) NOT NULL,
  `email` varchar(255) NOT NULL,
  `role` varchar(25) NOT NULL,
  `password` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;